<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNb0YWcP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNb0YWcP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNb0YWcP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNb0YWcP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNb0YWcP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nb0YWcP',
    'container.build_id' => '4605ac69',
    'container.build_time' => 1777848462,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNb0YWcP');
