<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPOwjOfH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPOwjOfH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPOwjOfH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPOwjOfH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPOwjOfH\App_KernelDevDebugContainer([
    'container.build_hash' => 'POwjOfH',
    'container.build_id' => '178e9470',
    'container.build_time' => 1777905894,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPOwjOfH');
